-- Kjør hele denne filen i Supabase: SQL Editor > New query > Run
create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  theory_id text not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  username text not null check (char_length(username) between 1 and 30),
  body text not null check (char_length(body) between 1 and 1000),
  created_at timestamptz not null default now()
);

create table if not exists public.votes (
  theory_id text not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  choice text not null check (choice in ('agree', 'disagree')),
  created_at timestamptz not null default now(),
  primary key (theory_id, user_id)
);

alter table public.comments enable row level security;
alter table public.votes enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'comments'
      and policyname = 'Comments are readable by everyone'
  ) then
    create policy "Comments are readable by everyone"
      on public.comments for select using (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'comments'
      and policyname = 'Users create their own comments'
  ) then
    create policy "Users create their own comments"
      on public.comments for insert to authenticated
      with check (auth.uid() = user_id);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'comments'
      and policyname = 'Users delete their own comments'
  ) then
    create policy "Users delete their own comments"
      on public.comments for delete to authenticated
      using (auth.uid() = user_id);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'votes'
      and policyname = 'Votes are readable by everyone'
  ) then
    create policy "Votes are readable by everyone"
      on public.votes for select using (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'votes'
      and policyname = 'Users create their own vote'
  ) then
    create policy "Users create their own vote"
      on public.votes for insert to authenticated
      with check (auth.uid() = user_id);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'votes'
      and policyname = 'Users update their own vote'
  ) then
    create policy "Users update their own vote"
      on public.votes for update to authenticated
      using (auth.uid() = user_id)
      with check (auth.uid() = user_id);
  end if;
end
$$;

create index if not exists comments_theory_created_idx on public.comments(theory_id, created_at desc);
create index if not exists votes_theory_idx on public.votes(theory_id);
