/* eslint-disable no-dupe-keys */
import { contentEn, contentUk } from './contentTranslations.js'
const en = {
  'Mer enn et spill':'More than a game','En verden som fortsatt vekker spørsmål':'A world that still raises questions','Dykk dypere på den offisielle siden':'Dive deeper on the official site','Karakterer':'Characters','Utvikling':'Development','Versjoner':'Versions','Det forbudte landet':'The Forbidden Lands','Utforsk verdenen':'Explore the world','Kolossene':'The Colossi','Historien':'The story','Verdenen':'The world','Teoriene':'The theories','Møt de enorme skapningene som vokter det forbudte landet.':'Meet the enormous creatures guarding the Forbidden Lands.','Oppdag Wander, Mono og kraften som hviler i landet.':'Discover Wander, Mono and the power resting within the land.','Utforsk ruinene, slettene og hemmelighetene mellom dem.':'Explore the ruins, plains and the secrets between them.','Les hva fans tror skjuler seg bak den åpne fortellingen.':'Read what fans believe lies behind the open-ended story.','Historien slutter ikke med spillet':'The story does not end with the game','Hva tror du skjedde?':'What do you think happened?','Utforsk fan-teorier →':'Explore fan theories →','Fanside for Shadow of the Colossus':'Shadow of the Colossus fan site','Ikke tilknyttet Sony Interactive Entertainment':'Not affiliated with Sony Interactive Entertainment',
  'Galleri':'Gallery','Arkiv fra det forbudte landet':'Archive of the Forbidden Lands','Filtrer samlingen for å se ruiner, konseptkunst, kolosser og miljøer fra spillet.':'Filter the collection to see ruins, concept art, colossi and environments from the game.','Alle':'All','Ruiner':'Ruins','Konseptkunst':'Concept art','Kolosser':'Colossi','Miljøer':'Environments','Det sunkne tempelet':'The sunken temple','Broene i det forbudte landet':'Bridges of the Forbidden Lands','En glemt sivilisasjon':'A forgotten civilization','Gaius i landskapet':'Gaius in the landscape','Veien til Malus':'The road to Malus','Fossene':'The waterfalls','Tåken ved innsjøen':'Mist by the lake','Kilde:':'Source:',
  'Kart':'Map','Utforsk kartet':'Explore the map','Dra kartet, zoom inn og velg en kategori for å finne stedene.':'Drag the map, zoom in and choose a category to find locations.','Helligdommer':'Shrines','Landemerker':'Landmarks','Nullstill':'Reset','Kartillustrasjon:':'Map illustration:','Zoom inn':'Zoom in','Zoom ut':'Zoom out','Velg type sted':'Choose location type','Kartkontroller':'Map controls',
  'Historier fra det forbudte landet':'Stories from the Forbidden Lands','Personer og krefter':'People and powers','Velg et navn for å lese mer om rollen deres i fortellingen.':'Choose a name to learn more about their role in the story.','Tilbake':'Back','Les mer om':'Read more about',
  'En ung kriger som trosser lovene i det forbudte landet for å bringe Mono tilbake.':'A young warrior who defies the laws of the Forbidden Lands to bring Mono back.','Den unge kvinnen Wander forsøker å redde, etter at hun ble ofret på grunn av en forbannet skjebne.':'The young woman Wander tries to save after she was sacrificed because of a cursed fate.','En eldgammel og tvetydig makt, delt i seksten deler og forseglet inne i kolossene.':'An ancient and ambiguous power, split into sixteen parts and sealed inside the colossi.','Sjamanen som vokter kunnskapen om landet og forsøker å hindre Dormin i å bli satt fri.':'The shaman who guards the knowledge of the land and tries to prevent Dormin from being freed.',
  'Fan-teorier':'Fan theories','Fra fellesskapet':'From the community','Hva skjuler det forbudte landet?':'What is hidden in the Forbidden Lands?','Utforsk teorier, stem på dem du tror på og del dine egne tanker.':'Explore theories, vote for those you believe and share your thoughts.','Alle temaer':'All topics','Andre spill':'Other games','Søk og filtrering':'Search and filters','Søk i teorier':'Search theories','Søk i teorier ...':'Search theories...','Tema':'Topic','teori':'theory','teorier':'theories','Ingen teorier funnet':'No theories found','Prøv et annet søkeord eller tema.':'Try another search term or topic.','Avstemning':'Poll','Hva tror du?':'What do you think?','Jeg tror på den':'I believe it','Ikke overbevist':'Not convinced','Tror på den':'Believe it','Takk for stemmen din! Stemmen er lagret.':'Thanks for voting! Your vote is saved.','Logg inn for å stemme.':'Sign in to vote.','Diskusjon':'Discussion','Hva tenker du?':'What do you think?','kommentarer':'comments','Skriv en kommentar':'Write a comment','Del tankene dine om teorien ...':'Share your thoughts about the theory...','Logg inn for å skrive en kommentar':'Sign in to write a comment','Lagrer ...':'Saving...','Publiser kommentar':'Post comment','Vis mindre ↑':'Show less ↑','Les hele teorien ↓':'Read the full theory ↓','Kilde og videre lesing ↗':'Source and further reading ↗','Lukk teori':'Close theory','stemmer':'votes',
  'Logg inn':'Sign in','Logg ut':'Sign out','Opprett konto':'Create account','Innlogget som':'Signed in as','Det forbudte landet':'The Forbidden Lands','Logg inn for å stemme og delta i diskusjonen.':'Sign in to vote and join the discussion.','Brukernavn':'Username','E-post':'Email','Passord':'Password','Vennligst vent ...':'Please wait...','Registrer deg':'Register','Ny her? Opprett en konto':'New here? Create an account','Har du konto? Logg inn':'Already have an account? Sign in','Sjekk e-posten din og bekreft kontoen før du logger inn.':'Check your email and confirm your account before signing in.','Lukk':'Close','Åpne innstillinger':'Open settings',
}

const uk = {
  'Mer enn et spill':'Більше, ніж гра','En verden som fortsatt vekker spørsmål':'Світ, який досі породжує питання','Dykk dypere på den offisielle siden':'Дізнайтеся більше на офіційному сайті','Karakterer':'Персонажі','Tutorial':'Навчання','Utvikling':'Розробка','Versjoner':'Версії','Det forbudte landet':'Заборонені землі','Utforsk verdenen':'Досліджуйте світ','Kolossene':'Колоси','Historien':'Історія','Verdenen':'Світ','Teoriene':'Теорії','Møt de enorme skapningene som vokter det forbudte landet.':'Зустріньте величезних істот, що охороняють Заборонені землі.','Oppdag Wander, Mono og kraften som hviler i landet.':'Дізнайтеся про Вандера, Моно та силу, що спочиває в цих землях.','Utforsk ruinene, slettene og hemmelighetene mellom dem.':'Досліджуйте руїни, рівнини та приховані між ними таємниці.','Les hva fans tror skjuler seg bak den åpne fortellingen.':'Прочитайте, що фанати думають про загадки відкритої історії.','Historien slutter ikke med spillet':'Історія не закінчується разом із грою','Hva tror du skjedde?':'Як ви думаєте, що сталося?','Utforsk fan-teorier →':'Переглянути фан-теорії →','Fanside for Shadow of the Colossus':'Фан-сайт Shadow of the Colossus','Ikke tilknyttet Sony Interactive Entertainment':'Не пов’язано із Sony Interactive Entertainment',
  'Galleri':'Галерея','Arkiv fra det forbudte landet':'Архів Заборонених земель','Filtrer samlingen for å se ruiner, konseptkunst, kolosser og miljøer fra spillet.':'Фільтруйте колекцію руїн, концепт-артів, колосів і краєвидів гри.','Alle':'Усі','Ruiner':'Руїни','Konseptkunst':'Концепт-арт','Kolosser':'Колоси','Miljøer':'Краєвиди','Det sunkne tempelet':'Затонулий храм','Broene i det forbudte landet':'Мости Заборонених земель','En glemt sivilisasjon':'Забута цивілізація','Gaius i landskapet':'Гай у краєвиді','Veien til Malus':'Шлях до Малуса','Fossene':'Водоспади','Tåken ved innsjøen':'Туман біля озера','Kilde:':'Джерело:',
  'Kart':'Мапа','Utforsk kartet':'Досліджуйте мапу','Dra kartet, zoom inn og velg en kategori for å finne stedene.':'Перетягуйте й масштабуйте мапу та оберіть категорію місць.','Helligdommer':'Святилища','Landemerker':'Орієнтири','Nullstill':'Скинути','Kartillustrasjon:':'Ілюстрація мапи:','Zoom inn':'Збільшити','Zoom ut':'Зменшити','Velg type sted':'Оберіть тип місця','Kartkontroller':'Керування мапою',
  'Historier fra det forbudte landet':'Історії Заборонених земель','Personer og krefter':'Персонажі та сили','Velg et navn for å lese mer om rollen deres i fortellingen.':'Оберіть ім’я, щоб дізнатися більше про його роль в історії.','Tilbake':'Назад','Les mer om':'Докладніше про',
  'En ung kriger som trosser lovene i det forbudte landet for å bringe Mono tilbake.':'Молодий воїн, який порушує закони Заборонених земель, щоб повернути Моно.','Den unge kvinnen Wander forsøker å redde, etter at hun ble ofret på grunn av en forbannet skjebne.':'Молода жінка, яку Вандер намагається врятувати після жертвопринесення через прокляту долю.','En eldgammel og tvetydig makt, delt i seksten deler og forseglet inne i kolossene.':'Давня неоднозначна сила, розділена на шістнадцять частин і запечатана в колосах.','Sjamanen som vokter kunnskapen om landet og forsøker å hindre Dormin i å bli satt fri.':'Шаман, який береже знання про землю й намагається не допустити звільнення Дорміна.',
  'Fan-teorier':'Фан-теорії','Fra fellesskapet':'Від спільноти','Hva skjuler det forbudte landet?':'Що приховують Заборонені землі?','Utforsk teorier, stem på dem du tror på og del dine egne tanker.':'Досліджуйте теорії, голосуйте та діліться власними думками.','Alle temaer':'Усі теми','Andre spill':'Інші ігри','Søk og filtrering':'Пошук і фільтри','Søk i teorier':'Пошук теорій','Søk i teorier ...':'Пошук теорій...','Tema':'Тема','teori':'теорія','teorier':'теорії','Ingen teorier funnet':'Теорій не знайдено','Prøv et annet søkeord eller tema.':'Спробуйте інший запит або тему.','Avstemning':'Голосування','Hva tror du?':'Що ви думаєте?','Jeg tror på den':'Я вірю','Ikke overbevist':'Не переконаний','Tror på den':'Вірять','Takk for stemmen din! Stemmen er lagret.':'Дякуємо! Ваш голос збережено.','Logg inn for å stemme.':'Увійдіть, щоб голосувати.','Diskusjon':'Обговорення','Hva tenker du?':'Що ви думаєте?','kommentarer':'коментарів','Skriv en kommentar':'Написати коментар','Del tankene dine om teorien ...':'Поділіться думками про теорію...','Logg inn for å skrive en kommentar':'Увійдіть, щоб написати коментар','Lagrer ...':'Збереження...','Publiser kommentar':'Опублікувати','Vis mindre ↑':'Показати менше ↑','Les hele teorien ↓':'Прочитати всю теорію ↓','Kilde og videre lesing ↗':'Джерело та додаткове читання ↗','Lukk teori':'Закрити теорію','stemmer':'голосів',
  'Logg inn':'Увійти','Logg ut':'Вийти','Opprett konto':'Створити акаунт','Innlogget som':'Ви ввійшли як','Logg inn for å stemme og delta i diskusjonen.':'Увійдіть, щоб голосувати й брати участь в обговоренні.','Brukernavn':'Ім’я користувача','E-post':'Електронна пошта','Passord':'Пароль','Vennligst vent ...':'Зачекайте...','Registrer deg':'Зареєструватися','Ny her? Opprett en konto':'Вперше тут? Створіть акаунт','Har du konto? Logg inn':'Уже маєте акаунт? Увійдіть','Sjekk e-posten din og bekreft kontoen før du logger inn.':'Перевірте пошту й підтвердьте акаунт перед входом.','Lukk':'Закрити','Åpne innstillinger':'Відкрити налаштування',
}

en.Lore = 'Lore'
uk.Lore = 'Історія світу'

const dictionaries = { en: { ...en, ...contentEn }, uk: { ...uk, ...contentUk } }
export function translate(language, text) { return dictionaries[language]?.[text] || text }
export function localize(language, value) {
  if (typeof value === 'string') return translate(language, value)
  if (Array.isArray(value)) return value.map(item => localize(language, item))
  if (value && typeof value === 'object') return Object.fromEntries(Object.entries(value).map(([key,item]) => [key, localize(language,item)]))
  return value
}
