import { usePreferences } from '../Preferences/usePreferences.js'
function TheoryDetail({ theory, expanded, onToggleExpanded, onClose, user, userVote, percent, saving, onVote, comments, commentText, onCommentChange, onSubmit, message }) {
  const { language, tr } = usePreferences()
  return <article className="theory-detail" id="theory-detail"><div className="detail-hero"><img src={theory.image} alt="" style={{objectPosition:theory.position}}/><button onClick={onClose} aria-label={tr('Lukk teori')}>×</button><div><span>{theory.category}</span><h2>{theory.title}</h2></div></div><div className="detail-content">
    <section className="theory-story"><p className="lead">{theory.excerpt}</p>{expanded&&theory.body.map(paragraph=><p key={paragraph}>{paragraph}</p>)}<button className="text-button" onClick={onToggleExpanded}>{tr(expanded?'Vis mindre ↑':'Les hele teorien ↓')}</button><a className="theory-source" href={theory.source} target="_blank" rel="noreferrer">{tr('Kilde og videre lesing ↗')}</a></section>
    <section className="theory-poll"><p className="theories-kicker">{tr('Avstemning')}</p><h3>{tr('Hva tror du?')}</h3><div className="poll-buttons"><button className={userVote==='agree'?'active':''} onClick={()=>onVote('agree')} disabled={Boolean(userVote)||saving}>{tr('Jeg tror på den')}</button><button className={userVote==='disagree'?'active':''} onClick={()=>onVote('disagree')} disabled={Boolean(userVote)||saving}>{tr('Ikke overbevist')}</button></div><div className="poll-labels"><span>{tr('Tror på den')}</span><strong>{percent}%</strong><span>{tr('Ikke overbevist')}</span></div><div className="poll-bar" role="img"><span style={{width:`${percent}%`}}/></div>{userVote&&<p className="thanks">{tr('Takk for stemmen din! Stemmen er lagret.')}</p>}{!user&&<p className="login-hint">{tr('Logg inn for å stemme.')}</p>}</section>
    <section className="theory-comments"><div className="comments-heading"><div><p className="theories-kicker">{tr('Diskusjon')}</p><h3>{tr('Hva tenker du?')}</h3></div><span>{comments.length} {tr('kommentarer')}</span></div>{message&&<p className="data-message" role="status">{tr(message)}</p>}<form onSubmit={onSubmit}><label htmlFor="comment">{tr('Skriv en kommentar')}</label><textarea id="comment" value={commentText} onChange={event=>onCommentChange(event.target.value)} placeholder={tr(user?'Del tankene dine om teorien ...':'Logg inn for å skrive en kommentar')} rows="4" disabled={!user}/><button disabled={!user||saving}>{tr(saving?'Lagrer ...':'Publiser kommentar')}</button></form>{comments.map(comment=><div className="comment" key={comment.id}><span>{comment.username.charAt(0).toUpperCase()}</span><div><strong>{comment.username}</strong><small>{new Date(comment.created_at).toLocaleString(language)}</small><p>{comment.body}</p></div></div>)}</section>
  </div></article>
}
export default TheoryDetail
